#服务端口
server:
  port: 8082

#spring:
#  application:
#    name: clientapp
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8080/eureka/

#consul配置
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: consulclient
 #sleuth+zipkin实现链路追踪
   zipkin:
     base-url: http://localhost:8901
   sleuth:
     sampler:
       percentage: 1.0

#consul端点启用和暴露
management:
  endpoints:
    web:
      exposure:
        include: '*'



